augmentations:
  use_custom: True
  use_simclr: False
  use_dino: False
  use_simsiam: False
  use_moco: False
  use_byol: False



  shape_invariances:
    random_crop:
      enabled: 1
      px: [64, 128]
    random_horizontal_flip:
      enabled: 1
      prob: 0.5
    random_vertical_flip:
      enabled: 1
      prob: 0.5
    random_rotation:
      enabled: 1
      degrees: [-90, 90]  # Extended to ±90°

  geometric_transformations:
    zoom:
      enabled: 1
      scale: [0.1, 0.15]  # Zoom range: 90% to 110%
    affine_translation:
      enabled: 1
      translate_percent: [0, 0.25]  # Up to 25% translation

  texture_invariances:
    gaussian_blur:
      enabled: 1
      sigma: [0.001, 1.0]  # Updated blur range
    noise:
      enabled: 0
      mean: [0.01, 0.08]
      std: [0.01, 0.08]
    clipping:
      enabled: 0  

  color_invariances:
    color_jitter:
      enabled: 1
      brightness: [0.8, 1.2]
      contrast: [0.8, 1.2]
      saturation: [0.9, 1.1]
    random_grayscale:
      enabled: 1
      prob: 0.2
    solarization:
      enabled: 0
      threshold: 128

normalization:
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]


# parameters for the simCLR augmentations if use_simclr is True
augmentations:
  use_simclr: True
  use_dino: False
  use_custom: False
  use_simsiam: False

  simclr_params:
    cj_prob: 0.8 # Color jitter probability
    cj_strength: 1.0 # Color jitter strength
    cj_bright: 0.8 # Color jitter brightness
    cj_contrast: 0.8  # Color jitter contrast
    cj_sat: 0.8 # Color jitter saturation
    cj_hue: 0.2 # Color jitter hue  
    min_scale: 0.08 # Minimum scale for random resized crop
    random_gray_scale: 0.2  # Random grayscale probability 
    gaussian_blur: 0.5  # Gaussian blur probability
    kernel_size: None # Gaussian blur kernel size
    sigmas: [0.1, 2] # Gaussian blur sigma range
    vf_prob: 0.0  # Vertical flip probability
    hf_prob: 0.5  # Horizontal flip probability
    rr_prob: 0.5  # Random rotation probability
    rr_degrees: [-0, 0]   # Random rotation degrees


  dino_params:
    global_crop_size: 224   # Global crop size
    global_crop_scale: [0.4, 1.0] # Global crop scale
    local_crop_size: 96  # Local crop size
    local_crop_scale: [0.05, 0.4] # Local crop scale
    n_local_views: 6    # Number of local views
    hf_prob: 0.5 # Horizontal flip probability
    vf_prob: 0.0 # Vertical flip probability
    rr_prob: 0.0 # Random rotation probability
    rr_degrees: [-10, 10] # Random rotation degrees
    cj_prob: 0.8 # Color jitter probability
    cj_strength: 0.5  # Color jitter strength
    cj_bright: 0.8 # Color jitter brightness
    cj_contrast: 0.8 # Color jitter contrast
    cj_sat: 0.4  # Color jitter saturation
    cj_hue: 0.2 # Color jitter hue
    random_gray_scale: 0.2 # Random grayscale probability
    gaussian_blur: [1.0, 0.1, 0.5] # Gaussian blur probability
    kernel_size: null # Gaussian blur kernel size
    sigmas: [0.1, 2] # Gaussian blur sigma range
    solarization_prob: 0.2 # Solarization probability

  simsiam_params:
    input_size: 224
    cj_prob: 0.8
    cj_strength: 1.0
    cj_bright: 0.4
    cj_contrast: 0.4
    cj_sat: 0.4
    cj_hue: 0.1
    min_scale: 0.2
    random_gray_scale: 0.2
    gaussian_blur: 0.5
    kernel_size: null
    sigmas: [0.1, 2]
    vf_prob: 0.0
    hf_prob: 0.5
    rr_prob: 0.0
    rr_degrees: null

  moco_params:
    cj_prob: 0.8
    cj_strength: 0.5
    cj_bright: 0.4
    cj_contrast: 0.4
    cj_sat: 0.4
    cj_hue: 0.1
    min_scale: 0.2
    random_gray_scale: 0.2
    gaussian_blur: 0.5
    kernel_size: null
    sigmas: [0.1, 2]
    vf_prob: 0.0
    hf_prob: 0.5
    rr_prob: 0.0
    rr_degrees: [-10, 10]

  byol_params:
  augmentations:
  use_byol: True
  use_simclr: False
  use_dino: False
  use_simsiam: False
  use_moco: False
  use_custom: False

byol_params:
  cj_prob: 0.8
  cj_strength: 1.0
  cj_bright: 0.4
  cj_contrast: 0.4
  cj_sat: 0.2
  cj_hue: 0.1
  min_scale: 0.08
  random_gray_scale: 0.2
  sigmas: [0.1, 2]
  kernel_size: null
  vf_prob: 0.0
  hf_prob: 0.5
  rr_prob: 0.0
  rr_degrees: null

  view1:
    gaussian_blur: 1.0
    solarization_prob: 0.0

  view2:
    gaussian_blur: 0.1
    solarization_prob: 0.2
